# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb65e9c657b6ec331227b53867d1ab8b28219a27b654a5cb0a253792fc56aa0cdf89deb79b441a560b14029ad8f4f83f6526e79fa63cf55be86693b15870b2bb

test:
  secret_key_base: 96e903a6224a20f3b66dbc99cb224b3bd555dd9f77cf20bea16745a5f0e026586bde32c08fe55041037f1897c29935f9baf293bb52e05a28b3e82c6adb74bc6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
